### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by willshepherdson** [csexton/corporate-tool#8]
Dragging and dropping doesn't appear to allow us to upload attachments.

Any guidance you'd be able to provide?

Thanks!

**Comment by csexton** [comment]
It's a feature that can be added, but for now I would add to Google drive or the like and post the link.

**Comment by willshepherdson** [comment]
Got it -- that makes sense. There is a note on the edit page underneath the textarea that says "Attach files by dragging & dropping, or pasting from the clipboard".

**Comment by csexton** [comment]
Ah, now I understand the confusion. Currently that only allows for image files, but can be opened up to other types as well.

**Comment by willshepherdson** [comment]
Ok, that makes sense -- thanks. I'll use Google Drive in the meantime.
